#docker-compose up
# if reset library use docker-compose down then docker-compose up but dont remove docker volume
version: '3.7'

services:
    #timetrackingwebapp

    flasktutorial:
        container_name: flasktutorial
        build: 
            context: ./flasktutorial #where Dockerfile to build
        volumes:
            - ./flasktutorial:/usr/src/app/flask-tutorial
        ports:
            - ${FACE_RECOGNITION_SERVER_PORT}:${FACE_RECOGNITION_SERVER_PORT}
        #environment: 
            #- FLASK_APP=run.py
        #command: flask run --host=0.0.0.0 --port=${FACE_RECOGNITION_SERVER_PORT}
        command: python3 run.py
        networks:
            - timetracking-net
        depends_on:
            - postgresqldb

    #python face_recognition

    postgresqldb:
        container_name: postgres
        image: postgres:12
        networks:
            - timetracking-net
        environment: 
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE_NAME}
            PG_DATA: /var/lib/postgresql/data
        ports: 
            - 5432:5432
        env_file:
            - .env
        volumes: 
            - pgdata:/var/lib/postgresql/data
networks: 
    timetracking-net:
volumes: 
    pgdata:
    imgdata:
    